### ISSUE TITLE
npm run scripts have node_modules/.bin on path

### ISSUE THREAD

**Issue by olizilla** [foundersandcoders/bouncer#7]
The scripts in a package.json `scripts` section are run with `./node_modules/.bin` on the `PATH` so you can just call the executables by name without the prefix... try a `npm run env | grep PATH` to see it.

so:

``` json
"test": "./node_modules/tape/bin/tape ./test/*.test.js | ./node_modules/.bin/tap-spec"
```

becomes:

``` json
"test": "tape ./test/*.test.js | tap-spec"
```

Nice!

See: https://docs.npmjs.com/misc/scripts#path

**Comment by FilWisher** [comment]
Solved by #9. Thanks Oli, I've spent too much time with Makefile.
